# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_money', '0005_auto_20160518_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-pub_date',), 'verbose_name': '\u043f\u043b\u0430\u0442\u0451\u0436', 'verbose_name_plural': '\u041f\u043b\u0430\u0442\u0435\u0436\u0438 \u042f\u043d\u0434\u0435\u043a\u0441.\u041a\u0430\u0441\u0441\u044b'},
        ),
    ]
